export type SeoService = {
  slug: string; title: string; eyebrow: string; description: string; price: string;
  intro: string; includes: string[]; faqs: { q: string; a: string }[];
};

export const seoServices: SeoService[] = [
  { slug: "peticion-familiar-i-130-miami", title: "Preparación de Petición Familiar I-130 en Miami", eyebrow: "PETICIONES FAMILIARES", description: "Preparación profesional del Formulario I-130 y organización de evidencia para peticiones familiares.", price: "Servicio desde $500", intro: "Te ayudamos a preparar y organizar tu petición familiar con un proceso claro, atención en español y revisión documental antes de presentar.", includes: ["Preparación del Formulario I-130", "Checklist personalizado de documentos", "Organización de evidencia de la relación familiar", "Revisión final del paquete"], faqs: [{q:"¿La tarifa incluye las tasas de USCIS?",a:"No. La tarifa corresponde al servicio de preparación documental; las tasas gubernamentales se pagan por separado."},{q:"¿Pueden garantizar la aprobación?",a:"No. La decisión corresponde exclusivamente a USCIS y ningún preparador puede garantizar un resultado."}] },
  { slug: "ajuste-de-estatus-i-485-miami", title: "Preparación de Ajuste de Estatus I-485 en Miami", eyebrow: "AJUSTE DE ESTATUS", description: "Preparación documental del Formulario I-485 para solicitantes elegibles en Miami y Florida.", price: "Paquetes desde $600", intro: "Organizamos los formularios y documentos de respaldo para que puedas presentar un paquete completo y ordenado.", includes: ["Preparación del Formulario I-485", "Checklist de evidencia civil y migratoria", "Coordinación de formularios relacionados", "Revisión final del paquete"], faqs: [{q:"¿Toda persona puede ajustar estatus?",a:"No. La elegibilidad depende de la categoría y del historial migratorio. Si necesitas asesoría legal, consulta con un abogado de inmigración."},{q:"¿Incluye la petición I-130?",a:"Disponemos de paquetes con I-130 e I-485 según el servicio contratado."}] },
  { slug: "permiso-de-trabajo-i-765-miami", title: "Solicitud o Renovación de Permiso de Trabajo I-765", eyebrow: "AUTORIZACIÓN DE EMPLEO", description: "Preparación del Formulario I-765 para solicitudes y renovaciones elegibles de permiso de trabajo.", price: "Servicio desde $100", intro: "Preparamos tu solicitud o renovación y te entregamos una lista clara de los documentos necesarios.", includes: ["Preparación del Formulario I-765", "Checklist según la categoría indicada", "Organización de documentos de respaldo", "Revisión final"], faqs: [{q:"¿Cuánto tarda USCIS?",a:"Los tiempos varían por categoría y oficina. Consulta el estimado vigente directamente en USCIS."},{q:"¿La tarifa incluye USCIS?",a:"No. Las tasas gubernamentales, cuando correspondan, se pagan por separado."}] },
  { slug: "ciudadania-n-400-miami", title: "Preparación de Ciudadanía N-400 en Miami", eyebrow: "NATURALIZACIÓN", description: "Preparación profesional del Formulario N-400 y organización de documentos para naturalización.", price: "Servicio desde $200", intro: "Te acompañamos en la preparación documental de tu solicitud de naturalización con atención bilingüe.", includes: ["Preparación del Formulario N-400", "Checklist de documentos", "Revisión de consistencia de la información", "Organización final"], faqs: [{q:"¿Incluye preparación para el examen?",a:"El alcance principal es la preparación documental. Confirma previamente si deseas servicios adicionales."},{q:"¿Garantizan la ciudadanía?",a:"No. USCIS determina la elegibilidad y toma la decisión final."}] },
  { slug: "impuestos-itin-miami", title: "Preparación de Impuestos e ITIN en Miami", eyebrow: "IMPUESTOS E ITIN", description: "Preparación de impuestos personales, formularios 1099 y solicitudes de ITIN en Miami.", price: "Impuestos desde $150", intro: "Recibe una lista de documentos, precio claro según la complejidad y atención personalizada en español o inglés.", includes: ["Revisión inicial de documentos", "Preparación de la declaración o Formulario W-7", "Explicación de próximos pasos", "Entrega segura"], faqs: [{q:"¿El precio es fijo?",a:"Depende del tipo de declaración, formularios, dependientes, créditos y complejidad."},{q:"¿Puedo solicitar ITIN sin declarar impuestos?",a:"El IRS exige normalmente adjuntar una declaración, salvo que aplique una excepción específica."}] },
  { slug: "traducciones-certificadas-uscis-miami", title: "Traducciones Certificadas para USCIS en Miami", eyebrow: "TRADUCCIONES", description: "Traducciones certificadas al inglés para documentos presentados ante USCIS y otros trámites.", price: "Cotización según documento", intro: "Traducimos documentos civiles y de respaldo con certificación del traductor y entrega digital.", includes: ["Traducción completa al inglés", "Certificación del traductor", "Formato claro y profesional", "Entrega digital"], faqs: [{q:"¿Qué documentos traducen?",a:"Entre otros: actas, certificados, sentencias, constancias y documentos de respaldo."},{q:"¿Cómo recibo una cotización?",a:"Envía una imagen legible del documento por WhatsApp para revisar extensión, idioma y plazo."}] },
];

export function findSeoService(slug: string) { return seoServices.find((service) => service.slug === slug); }
