"use client";
import Image from "next/image";
import Link from "next/link";
import type { SeoService } from "@/lib/seo-services";

export default function ServicePage({ service, campaign = "seo" }: { service: SeoService; campaign?: string }) {
  const text = encodeURIComponent(`Hola María, vi la página de ${service.title} y quisiera más información.`);
  const whatsapp = `https://wa.me/13054823406?text=${text}`;
  const track = (name: string) => { const w = window as typeof window & { dataLayer?: Record<string, unknown>[] }; w.dataLayer?.push({ event: name, service: service.slug, campaign }); };
  return <main className="min-h-screen bg-slate-50 text-slate-900">
    <header className="border-b border-slate-200 bg-white"><div className="mx-auto flex max-w-6xl items-center justify-between px-5 py-4"><Link href="/"><Image src="/basevi-logo.webp" alt="Basevi Solutions" width={160} height={55} /></Link><a href="tel:+13054823406" onClick={() => track("phone_click")} className="font-semibold text-blue-900">(305) 482-3406</a></div></header>
    <section className="bg-gradient-to-br from-blue-950 via-blue-900 to-sky-800 text-white"><div className="mx-auto grid max-w-6xl gap-10 px-5 py-16 md:grid-cols-[1.4fr_.8fr] md:py-24"><div><p className="mb-4 text-sm font-bold tracking-[.18em] text-amber-300">{service.eyebrow}</p><h1 className="max-w-4xl text-4xl font-bold leading-tight md:text-6xl">{service.title}</h1><p className="mt-6 max-w-3xl text-lg leading-8 text-blue-100">{service.intro}</p><div className="mt-8 flex flex-wrap gap-4"><a href={whatsapp} onClick={() => track("whatsapp_click")} className="rounded-full bg-emerald-500 px-6 py-3 font-bold text-white shadow-lg">Hablar por WhatsApp</a><a href="https://calendly.com/mbasevim/30min" onClick={() => track("book_consultation_click")} className="rounded-full border border-white/50 px-6 py-3 font-bold">Agendar evaluación</a></div></div><aside className="rounded-3xl bg-white p-7 text-slate-900 shadow-2xl"><p className="text-sm font-bold text-blue-700">PRECIO DEL SERVICIO</p><p className="mt-2 text-3xl font-bold">{service.price}</p><p className="mt-4 text-sm leading-6 text-slate-600">Las tarifas gubernamentales y costos de terceros no están incluidos.</p><a href={whatsapp} onClick={() => track("whatsapp_click")} className="mt-6 block rounded-xl bg-blue-900 px-5 py-3 text-center font-bold text-white">Consultar mi caso</a></aside></div></section>
    <section className="mx-auto grid max-w-6xl gap-12 px-5 py-16 md:grid-cols-2"><div><h2 className="text-3xl font-bold text-blue-950">Qué incluye el servicio</h2><ul className="mt-6 space-y-4">{service.includes.map((item) => <li key={item} className="flex gap-3"><span className="font-bold text-emerald-600">✓</span><span>{item}</span></li>)}</ul></div><div><h2 className="text-3xl font-bold text-blue-950">Preguntas frecuentes</h2><div className="mt-6 space-y-4">{service.faqs.map((faq) => <details key={faq.q} className="rounded-xl border border-slate-200 bg-white p-5"><summary className="cursor-pointer font-bold">{faq.q}</summary><p className="mt-3 leading-7 text-slate-600">{faq.a}</p></details>)}</div></div></section>
    <section className="bg-blue-950 px-5 py-14 text-center text-white"><h2 className="text-3xl font-bold">Da el próximo paso con claridad</h2><p className="mx-auto mt-3 max-w-2xl text-blue-100">Cuéntanos qué necesitas y te explicaremos el alcance del servicio antes de comenzar.</p><a href={whatsapp} onClick={() => track("whatsapp_click")} className="mt-7 inline-block rounded-full bg-emerald-500 px-7 py-3 font-bold">Escribir por WhatsApp</a></section>
    <footer className="bg-white px-5 py-8 text-center text-sm leading-6 text-slate-500">Basevi Solutions LLC ofrece servicios de preparación documental. No es un bufete de abogados, no brinda asesoría legal ni representa ante USCIS o tribunales.</footer>
  </main>;
}
